templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/15
=> 15: Rename MustSupport in Data Requirements table

templates/liquid/Measure.liquid
Best looked at with the 8.5 Measure-HIVViralSuppressionFHIR.html library.
=> Cqf 1963 no blanks population

templates/liquid/ActivityDefinition.liquid, templates/liquid/Library.liquid, templates/liquid/Measure.liquid, templates/liquid/PlanDefinition.liquid
Removed unsupported elements from ActivityDefinition template
=> #9: Removed unsupported typecast from all templates

templates/liquid/Measure.liquid
=> #49: Wrapped SDE fields in <p> </p> so that their line breaks appear

templates/liquid/Measure.liquid
=> #51 Rate Aggregation .value cell colspan set to 3

templates/liquid/Measure.liquid
=> #48 Applying existing structure from Supplemental Data Elements to Risk Adjustment Factor

templates/liquid/ActivityDefinition.liquid, templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/40
=> 40: Added .name to author entry to get name to display.

templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/52
=> #52: Removing download cql link

templates/liquid/ActivityDefinition.liquid, templates/liquid/Library.liquid, templates/liquid/Measure.liquid, templates/liquid/PlanDefinition.liquid
https://github.com/cqframework/sample-content-ig/issues/46
=> #46: Removed name field, retaining title field.

templates/liquid/Measure.liquid
=> #50: reordered the SDE and RAV fields

templates/liquid/Measure.liquid
=> #48: Fixed issues with list and placement

templates/liquid/ActivityDefinition.liquid, templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/68
=> 68: Removed extra space

templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/71
=> 71: Updated url for cqfm-type

templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/73
=> 73: Added 'Applies To' extension

templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/87
=> 87: Renamed fields

templates/liquid/ActivityDefinition.liquid, templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/86
=> 86: Renamed fields

templates/liquid/ActivityDefinition.liquid, templates/liquid/Library.liquid, templates/liquid/Measure.liquid, templates/liquid/PlanDefinition.liquid
https://github.com/cqframework/sample-content-ig/issues/67
=> 67: Removed Date and Last Review Date

templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/69
=> 69: Updated colSpan value for group scoring

templates/liquid/Measure.liquid
https://github.com/cqframework/sample-content-ig/issues/70
=> 70: Stratum labeling

input-cache/txcache/all-systems.cache, input-cache/txcache/cs-externals.json, input-cache/txcache/loinc.cache, input-cache/txcache/snomed.cache, templates/liquid/contactdetail-list.html, templates/liquid/contactdetail.html, templates/liquid/knowledge-artifact-metadata.html, templates/liquid/measure-definition.html, templates/liquid/measure-identifier.html, templates/liquid/measure-metadata-extensions.html, templates/liquid/measure-metadata.html
- Added definitionTerm to the measure metadata extension resolution
- Removed Measure.definition
- Updated Measure Identifier and ContactDetail resolution to not use the built-in processing
Resolution for #121
=> Updates for Measure Liquid Narrative

_refresh.bat, _refresh.sh, _updateCQFTooling.bat, _updateCQFTooling.sh
=> Update cqf tooling version
